#!/usr/bin/env bash
# Build dist/bundle.md — the whole kit as one file, for pasting into ChatGPT Projects,
# a custom GPT, or a Gemini Gem where per-file uploads are capped.
#
# Usage:  bash scripts/build-bundle.sh
#
# dist/ is gitignored: the bundle is a build artifact, generated on demand right before an
# upload, never committed and never hand-edited. What it packs and what it deliberately
# leaves out is one rule, stated once in reference/README.md → 什么进 bundle.

set -euo pipefail
cd "$(dirname "$0")/.."

OUT="dist/bundle.md"
mkdir -p dist

{
  cat <<'HEADER'
# CoC Keeper Kit — Bundle

Generated by `scripts/build-bundle.sh`. Do not edit by hand.

This file contains every part of the kit that is the kit's own work: the routing adapter,
every `core/` spec, every template, and all of `reference/` except the third-party archives
(`decks/`, `sourcebooks/`, `og_Norval/`, `external/`) — see `reference/README.md` → 什么进
bundle. Each section is delimited by a line of the form:

    === FILE: core/04-design-scenario.md ===

Treat each section exactly as if it were a separate file at that path. When you tell the
Keeper where to save generated output, use those same paths.

Start by reading `core/00-how-to-run.md` below.

---

HEADER

  for f in AGENTS.md \
           core/*.md \
           templates/*.md \
           reference/README.md \
           reference/glossary-zh.md \
           reference/rules/*.md      reference/rules/*/*.md \
           reference/craft/*.md      reference/craft/*/*.md \
           reference/tables/*.md     reference/tables/*/*.md \
           reference/bestiary/*.md   reference/bestiary/*/*.md \
           reference/mythos/*.md     reference/mythos/*/*.md \
           campaigns/_template-campaign/CLAUDE.md \
           campaigns/_template-campaign/canon-log.md \
           campaigns/_template-campaign/overview.md; do
    [ -f "$f" ] || continue
    printf '\n=== FILE: %s ===\n\n' "$f"
    cat "$f"
    printf '\n'
  done
} > "$OUT"

printf 'Wrote %s (%s lines, %s files)\n' \
  "$OUT" \
  "$(wc -l < "$OUT" | tr -d ' ')" \
  "$(grep -c '^=== FILE: ' "$OUT")"
